# Imagen base
FROM python:3.12-slim

# Crear carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiar requirements
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar TODO el contenido del backend (así evita el error de rutas)
COPY backend/ /app/

# Comando para iniciar FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
